apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-boot-app
  labels:
    app: sprint-boot-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sprint-boot-app
  template:
    metadata:
      labels:
        app: sprint-boot-app
    spec:
      containers:
      - name: sprint-boot-app
        image: rabi4450/ultimate-cicd:1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service
spec:
  selector:
    app: sprint-boot-app
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: LoadBalancer
