apiVersion: apps/v1
kind: Deployment
metadata:
  name: myjavaapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myjavaapp
  template:
    metadata:
      labels:
        app: myjavaapp
    spec:
      containers:
      - name: myjavaapp
        image: rabi4450/redditapp1:latest
        ports:
        - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: myjavaapp-service
spec:
  selector:
    app: myjavaapp
  ports:
  - name: http
    port: 80
    targetPort: 9000
  type: LoadBalancer
