apiVersion: apps/v1
kind: Deployment
metadata:
  name: sprint-boot-app
  labels:
    app: sprint-boot-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-todo-app
  template:
    metadata:
      labels:
        app: node-todo-app
    spec:
      containers:
      - name: sprint-boot-app
        image: rabi4450/node-todo-test:latest
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: testjavaapp-service
spec:
  selector:
    app: node-todo-app
  ports:
  - name: http
    port: 80
    targetPort: 8000
  type: LoadBalancer
